### ISSUE TITLE
Argument error when trying to use Schizo

### ISSUE THREAD

**Issue by danielres** [cjbottaro/schizo#20]
Hi,

I have a strange error with the following code, using Rails4:

```
class ViewingAnEntry

  def initialize(viewer, entry, view_context)
    @viewer = viewer
    @entry = entry
    @view_context = view_context
  end

  def view
    @entry.as(Taggable) do |entry|
      h.render(partial: 'projects/project', project: entry) if h.can?(:read, entry)
    end
  end

  private

    def h
      @view_context
    end

    module Taggable
      extend Schizo::Role
      included do
        acts_as_taggable_on :skills
      end
    end

end
```

The error, in terminal:

```
ArgumentError - wrong number of arguments (0 for 1):
  app/contexts/viewing_an_entry.rb:23:in `<module:Taggable>'
  app/contexts/viewing_an_entry.rb:21:in `<class:ViewingAnEntry>'
  app/contexts/viewing_an_entry.rb:1:in `<top (required)>'
```

The error refers to the line containing `included do`

Seems like a dumb mistake from me somewhere, but I can't figure it out...
Am I missing something ?

Here is my controller:

```
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  def show
    project = Project.find(params[:id])
    render layout: true,
             text: ::ViewingAnEntry.new(current_user, project, view_context).view
  end

end
```

And my model:

```
class Project < ActiveRecord::Base
  include Schizo::Data
end
```

Any suggestion would we really appreciated, I'd love to be able to use schizo in my project :)
Thank you.

**Comment by danielres** [comment]
Ok, I found a workaround to my problem:

I had to change from:

```
    module Taggable
      extend Schizo::Role
      included do
        acts_as_taggable_on :skills
      end
    end
```

to:

```
    module Taggable
      extend Schizo::Role
      def self.extended(base)
        base.class.class_eval do
          acts_as_taggable_on :skills
        end
      end
    end
```

**Comment by danielres** [comment]
I had also to change my code from:

```
    @entry.as(Taggable) do |entry|
      h.render(partial: 'projects/project', project: entry) if h.can?(:read, entry)
    end
```

to: 

```
    entry = @entry.as(Taggable)
    h.render(partial: 'projects/project', project: entry) if h.can?(:read, entry)
```

**Comment by andriytyurnikov** [comment]
Hello @danielres .
Allow me to make few comments to get us on same page :)
1) _Enclosing_ role within a class is an unexpected move :) but this is not relevant to the case
2) When you use block, role is only visible within a block by design:

``` ruby
@entry.as(Taggable) do |taggable_entry_within_block|
  taggable_entry_within_block.has_taggable_methods_only_within_block # by design
end

@entry # has no methods of Taggable role out of the block (:
# also it has no role methods within a block - another wrapper object is used within a block, and instance variables are copied between wrapper and original, after block executes

```

3) When you don't use block, you recieve wrapper object:

``` ruby
taggable_entry = @entry.as(Taggable)
taggable_entry # is not actualy equal to @entry, it is a wrapper object, that behaves *like* @entry with role methods
```

We looking for magic powers that would help us to avoid this (:

4) Thanks for your feedback, misuse of library is a smell of lack of clarity (:

**Comment by andriytyurnikov** [comment]
@danielres also I really want to highlight the fact that roles are not really just about adding functionality ( concerns can handle that ), but about being able to remove functionality, so roles are isolated and independent on each other (concerns do not handle that, schizo does)
